config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'users#index'

  resources :contents, only: [:new,:create,:index,:show] do
    resources :photos, only: [:create]
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end

#userリソースに対する、/:id/following, /:id/followers　のルーティングを定義
#memberは、users/:id/xxxx となり、 collectは、 users/xxx となる
  resources :users do
    member do
     get :following, :followers
    end
  end
  resources :relationships,       only: [:create, :destroy]
end

app/models/content.rb
class Content < ApplicationRecord
  belongs_to :user
  has_many :photos, dependent: :destroy
  has_many :likes, -> { order(created_at: :desc) }, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
  has_many :comments, dependent: :destroy
  accepts_nested_attributes_for :photos


  def liked_by(user)
    # user_idとpost_idが一致するlikeを検索する
    Like.find_by(user_id: user.id, content_id: id)
  end
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
   include ContentsHelper

  def index
    @contents = Content.limit(10).includes(:photos, :user).order('created_at DESC')
    @users = User.all

    @contents_ids = following_user_contents_ids(current_user)
  end

  def show
    @content = Content.find_by(id: params[:id])
    @user = @content.user_id
  end

  def new
    @content = Content.new
    @content.photos.build
  end

  def create
    @content = Content.new(content_params)
    if @content.save
      redirect_to root_path
      flash[:notice] = "投稿が保存されました"
    else
      redirect_to root_path
      flash[:alert] = "投稿に失敗しました"
    end
  end

    private
      def content_params
        params.require(:content).permit(:name,:description, photos_attributes: [:image]).merge(user_id: current_user.id)
      end

      def following_user_contents_ids(owner)
        following_user_ids = owner.following_ids
        contents_ids = []
        following_user_ids.each do |user_id|
          contents_ids.concat(User.find(user_id).content_ids)
        end

        return contents_ids.sort
      end

end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/views/contents/_comment_list.html.erb
<% content.comments.each do |comment| %>
  <div class="mb-2">
    <% if comment.user == current_user %>
      <%= link_to "コメント削除", content_comment_path(content.id, comment), method: :delete, remote: true, class: "delete-comment" %>
    <% end %>
    <span>
      <strong>
        <%= link_to comment.user.name, user_path(comment.user), class: "no-text-decoration black-color" %>
      </strong>
    </span>
    <span><%= comment.comment %></span>
  </div>
<% end %>

app/views/contents/_like_text.html.erb
<strong>
  <% likes.each.with_index do |like, index| %>
    <% if likes.size == 1 %>
      <%= like.user.name %> </strong> が「いいね！」しました
    <% elsif like == likes.last %>
      </strong>and<strong>
      <%= + like.user.name %></strong> が「いいね！」しました
    <% elsif index > 1 %>
      </strong><%= "and " + (likes.size-index).to_s + " 他 " %> が「いいね！」しました
      <% break %>
    <% elsif index == likes.size-2 || index == 1 %>
      <%= like.user.name %>
    <% else %>
      <%= like.user.name + ", " %>
    <% end %>
  <% end %>
</strong>

app/views/contents/index.html.erb
<div id="script-check">
  <h1>じゃゔぁすくりぷとちぇっく</h1>
  <%if current_user  %>
    <%= "#{current_user.name}さんがログインしています"%>
  <%end%>
</div>


<div class="card">
  <div class="card-body">
  <% @users.each do |user| %>
   <% user.contents.each do |content| %>
    <p><%= content.name %>さんの投稿</p>
    <p><%= link_to content.user.name , user_path(user) %> </p>
    <p><%= content.description %></p>
    <%= link_to time_ago_in_words(content.created_at).upcase + "前", "#" %>

      <% content.photos.each do |photo| %>
        <%= link_to (content_path(photo.content.id)) do %>
          <%= image_tag photo.image.thumb.url %>
        <% end %>
      <% end %>
    <div id="like-icon-post-<%= content.id.to_s %>">
      <% if content.liked_by(current_user).present? %>
        <%= link_to "いいねを取り消す", content_like_path(content.id, content.liked_by(current_user)), method: :DELETE, remote: true, class: "loved hide-text" %>
      <% else %>
          <%= link_to "いいね", content_likes_path(content), method: :POST, remote: true, class: "love hide-text" %>
      <% end %>
    </div>
    <div id="like-text-post-<%= content.id.to_s %>">
        <%= render "like_text", { likes: content.likes } %>
   </div>

    <div id="comment-post-<%= content.id.to_s %>">
       <%= render 'comment_list', { content: content } %>
    </div>
        <%= link_to time_ago_in_words(content.created_at).upcase + "前", content_path(content),
        class: "light-color post-time no-text-decoration" %>
        <hr>
     <div class="row actions" id="comment-form-post-<%= content.id.to_s %>">
       <%= form_with model: [content, Comment.new], class: "w-100" do |f| %>
       <%= f.hidden_field :user_id, value: current_user.id %>
       <%= f.hidden_field :content_id, value: content.id %>
       <%= f.text_field :comment, class: "form-control comment-input border-0", placeholder: "コメント ...", autocomplete: :off %>
       <%= f.submit "コメント送信", class: "btn btn-large btn-primary follow-btn" %>
     <% end %>
     </div>
     <h2>以下にリツイート的な機能を実装</h2>
     <%= form_with model: [current_user, Content.new], url: contents_path, method: :post  do |f| %>

         <%= f.hidden_field :name, value: "#{content.name}"%>
         <%= f.text_field :description,value: "#{content.description}" %>
         <% if content.photos.present? %>
          <%= f.text_field :image, value: "#{content.photos.first.image.url}" %>
         <% end %>
         <%= f.fields_for :photos do |i| %>
         <%= i.file_field :image %>
       <% end %>
       <%= f.submit "積む!!!!!!!!", class: "btn btn-primary" %>
       <% end %>
       </div>


     <h2>以上にリツイート的な機能を実装</h2>
     </div>

   <% end %>
   <% end %>

  </div>
</div>

<h1>以下にフォローしているユーザーの投稿を表示</h1>
<% @contents_ids.each do |content_id| %>
<% content = Content.find(content_id) %>
   <% if content.photos.present?%>
     <% photo = content.photos.first%>
     <%= image_tag photo.image.thumb.url %>
   <% end %>
 <p><%= "#{content.user.name} さん" %></p>
  <%= link_to time_ago_in_words(Content.find(content_id).created_at).upcase + "前", "#" %>
<% end %>

app/views/contents/new.html.erb
<%= form_with model: @content do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.fields_for :photos do |i| %>
    <%= i.file_field :image %>
  <% end %>
  </div>

  <div class="field">
    <%= f.label :description  %>
    <%= f.text_field :description %>
  </div>

  <%= f.submit "投稿", class: "btn btn-primary" %>
<% end %>

app/views/contents/show.html.erb
<p><%= @content.user.name %></p>
<p><%= @content.name %></p>
<p><%= @content.description %></p>
<%= link_to user_path(@content.user)  %>
<h2>アバターイメージ</h2>
<%= image_tag (@content.user.avatar.avatar_image.url) %>
<%= link_to user_path(@content.user) %>
<strong><%= @content.user.name %></strong>

<h2>コンテンツイメージ</h2>
<% @content.photos.each do |photo| %>
    <%= image_tag photo.image.thumb.url %>
<% end %>