config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'users#index'

  resources :contents, only: [:new,:create,:index,:show] do
    resources :photos, only: [:create]
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end

#userリソースに対する、/:id/following, /:id/followers　のルーティングを定義
#memberは、users/:id/xxxx となり、 collectは、 users/xxx となる
  resources :users do
    member do
     get :following, :followers
    end
  end
  resources :relationships,       only: [:create, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :avatar, AvatarUploader
  validates :email, presence: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable,
         :validatable

  has_many :contents, dependent: :destroy
  has_many :likes
  has_many :liked_posts, through: :likes, source: :content
  has_many :comments

  has_many :following_relationships, foreign_key: "follower_id",
    class_name: "Relationship", dependent: :destroy
  has_many :followings, through: :following_relationships

  has_many :follower_relationships, foreign_key: "following_id",
    class_name: "Relationship", dependent: :destroy
  has_many :followers, through: :follower_relationships

  def following?(other_user)
   following_relationships.find_by(following_id: other_user.id)
  end

  def follow!(other_user)
   following_relationships.create!(following_id: other_user.id)
  end

  def unfollow!(other_user)
   following_relationships.find_by(following_id: other_user.id).destroy
  end


end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
  def after_update_path_for(resource)
      user_path(resource)
  end

end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
    @user = current_user
  end

  def show
      @user = User.find_by(id: params[:id])
      @contents = @user.contents
      @mycontents_count = @user.contents.ids.count
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = "#{@user} のプロフィールを編集が完了しました"
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  def following
      @user  = User.find(params[:id])
      @users = @user.followings
      render 'show_follow'
  end

  def followers
    @user  = User.find(params[:id])
    @users = @user.followers
    render 'show_follower'
  end

 private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation,:avatar)
  end

  def set_user
   @user = User.find(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def current_user?(user)
     user == current_user
  end
end

app/views/users/_follow.html.erb
<%= form_for(current_user.following_relationships.build(following_id: @user.id),remote: true) do |f| %>
  <div><%= f.hidden_field :following_id %></div>
  <%= f.submit "Follow", class: "btn btn-large btn-primary follow-btn" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= form_for(current_user.following_relationships.find_by(following_id: @user.id),remote: true, html: { method: :delete }) do |f| %>
    <%= f.submit "Unfollow", class: "btn btn-large follow-btn" %>
    <% end %>
  <% else %>
    <%= form_for(current_user.following_relationships.build(following_id: @user.id),remote: true) do |f| %>
    <div><%= f.hidden_field :following_id %></div>
    <%= f.submit "Follow", class: "btn btn-large btn-primary follow-btn" %>
    <% end %>
  <% end %>
  </div>
<% end %>

app/views/users/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
 <a href="<%= following_user_path(@user) %>">
   <strong id="following" class="stat">
     <%= @user.followings.count %>
   </strong>
   following
 </a>
 <a href="<%= followers_user_path(@user) %>">
   <strong id="followers" class="stat">
     <%= @user.followers.count %>
   </strong>
   followers
 </a>
</div>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.following_relationships.find_by(following_id: @user.id), html: { method: :delete }) do |f| %>
  <%= f.submit "Unfollow", class: "btn btn-large follow-btn" %>
<% end %>

app/views/users/edit.html.erb
<%= form_for(@user) do |f| %>
   <% if @user.avatar? %>
      <%= image_tag @user.avatar.url %>
   <% else %>
      <%= image_tag "/assets/default.jpg", :size => '100x100' %>
   <% end %>
    <div class="field">
        <%= f.label :avatar %>
      <button type="button" class="btn btn-outline-secondary rounded-pill">
         <%= f.file_field :avatar, accept: 'image/jpeg,image/gif,image/png' %>
      </button>
    </div>

    <div class="field">
        <%= f.label :name %><br />
        <%= f.text_field :name, autofocus: true, placeholder: "tsundoku@gmail.com" %>
    </div>
　　<%= f.submit '更新する', class: 'btn btn-primary' %>
<% end %>

app/views/users/index.html.erb
<h1>全てのユーザー</h1>

<ul>
  <% @users.each do |user| %>
    <li>
      <% if user.avatar? %>
        <%= image_tag user.avatar.avatar_image.url , class: 'avatar_image' %>
      <% else %>
        <p>イメージ未登録</p>
      <% end %>
      <%= link_to user.name, user_path(user.id) %>
    </li>
  <% end %>
</ul>

app/views/users/show.html.erb
<div id="script-check">
  <h1>じゃゔぁすくりぷとちぇっく</h1>
</div>

<h1><%= @user.name %>のページ</h1>
<h6><%= @mycontents %>積んでいます</h6>

 <% if user_signed_in? %>
 <div id ="following_form">
   <%= render 'follow_form'%>
 </div>

<div id ="follow_counter">
  <%= render 'stats'%>
</div>

  <%= link_to "パスワードを変更する", edit_user_registration_path, class: "btn btn-outline-dark common-btn edit-profile-btn" %>

  <%= link_to "サインアウト", destroy_user_session_path, method: :delete, class: "list-group-item list-group-item-action" %>

  <%= link_to "プロフィールを編集", edit_user_path(@user), class: "list-group-item list-group-item-action" %>

  <%= link_to "キャンセル", "#", class: "list-group-item list-group-item-action", "data-dismiss": "modal" %>
<% end %>

<%= @user.email %></h1>

<div>
    <% if @user.avatar? %>
    <%= image_tag @user.avatar.avatar_image.url %>
    <% else %>
    <p>No Image</p>
    <% end %>
</div>

 <% if @user == current_user %>
   <div class="row">
     <p>
       <%= @user.email %>
     </p>
   </div>
  <% end %>

  <div class="card">
    <div class="card-body">
     <% @user.contents.each do |content| %>
      <p><%= content.name %>さんの投稿</p>
      <p><%= content.description %></p>
      <%= link_to time_ago_in_words(content.created_at).upcase + "前", "#" %>
        <% content.photos.each do |photo| %>
          <%= link_to (content_path(photo.content.id)) do %>
            <%= image_tag photo.image.thumb.url %>
          <% end %>
        <% end %>
     <% end %>
   </div>
   </div>

app/views/users/show_follow.html.erb
<% @user.followings.each do |user| %>
<table>
<tr>
  <td>  <%= user.username %> </td>
  <td><%= link_to '詳細', user_path(user) %></td>
</tr>

</table>
<% end %>

app/views/users/show_follower.html.erb
<% @user.followers.each do |user| %>
<table>
<tr>
 <td>  <%= user.username %> </td>
 <td><%= link_to '詳細', user_path(user) %></td>
</tr>

</table>
<% end %>