config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'users#index'

  resources :contents, only: [:new,:create,:index,:show] do
    resources :photos, only: [:create]
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end

#userリソースに対する、/:id/following, /:id/followers　のルーティングを定義
#memberは、users/:id/xxxx となり、 collectは、 users/xxx となる
  resources :users do
    member do
     get :following, :followers
    end
  end
  resources :relationships,       only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :content
  validates :user_id, uniqueness: { scope: :content_id }
end

app/models/content.rb
class Content < ApplicationRecord
  belongs_to :user
  has_many :photos, dependent: :destroy
  has_many :likes, -> { order(created_at: :desc) }, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
  has_many :comments, dependent: :destroy
  accepts_nested_attributes_for :photos


  def liked_by(user)
    # user_idとpost_idが一致するlikeを検索する
    Like.find_by(user_id: user.id, content_id: id)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :content
  validates :user_id, uniqueness: { scope: :content_id }
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :content
  mount_uploader :image, ImageUploader
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :following, class_name: "User"
  belongs_to :follower, class_name: "User"
  
  validates :follower_id, presence: true
  validates :following_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :avatar, AvatarUploader
  validates :email, presence: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable,
         :validatable

  has_many :contents, dependent: :destroy
  has_many :likes
  has_many :liked_posts, through: :likes, source: :content
  has_many :comments

  has_many :following_relationships, foreign_key: "follower_id",
    class_name: "Relationship", dependent: :destroy
  has_many :followings, through: :following_relationships

  has_many :follower_relationships, foreign_key: "following_id",
    class_name: "Relationship", dependent: :destroy
  has_many :followers, through: :follower_relationships

  def following?(other_user)
   following_relationships.find_by(following_id: other_user.id)
  end

  def follow!(other_user)
   following_relationships.create!(following_id: other_user.id)
  end

  def unfollow!(other_user)
   following_relationships.find_by(following_id: other_user.id).destroy
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :avatar])
      devise_parameter_sanitizer.permit(:account_update, keys: [:name, :avatar,])
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :authenticate_user!


  def create
    @comment = Comment.new(comment_params)
    @content = @comment.content
    if @comment.save
      respond_to :js
    else
      flash[:alert] = "コメントに失敗しました"
    end
  end

  def destroy
    @comment = Comment.find_by(id: params[:id])
    @content = @comment.content
    if @comment.destroy
      respond_to :js
    else
      flash[:alert] = "コメントの削除に失敗しました"
    end
  end

  private
    def comment_params
      params.require(:comment).permit(:user_id, :content_id, :comment)
    end

end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
   include ContentsHelper

  def index
    @contents = Content.limit(10).includes(:photos, :user).order('created_at DESC')
    @users = User.all

    @contents_ids = following_user_contents_ids(current_user)
  end

  def show
    @content = Content.find_by(id: params[:id])
    @user = @content.user_id
  end

  def new
    @content = Content.new
    @content.photos.build
  end

  def create
    @content = Content.new(content_params)
    if @content.save
      redirect_to root_path
      flash[:notice] = "投稿が保存されました"
    else
      redirect_to root_path
      flash[:alert] = "投稿に失敗しました"
    end
  end

    private
      def content_params
        params.require(:content).permit(:name,:description, photos_attributes: [:image]).merge(user_id: current_user.id)
      end

      def following_user_contents_ids(owner)
        following_user_ids = owner.following_ids
        contents_ids = []
        following_user_ids.each do |user_id|
          contents_ids.concat(User.find(user_id).content_ids)
        end

        return contents_ids.sort
      end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
 before_action :authenticate_user!

  def create
    #この@likeには、current_userの user_id と、content_idが保存される
    @like = current_user.likes.build(like_params)
    @content = @like.content
    if @like.save
      respond_to :js
    end
  end

  def destroy
    @like = Like.find_by(id: params[:id])
    @content = @like.content
    if @like.destroy
      respond_to :js
    end
  end

private
  def like_params
    params.permit(:content_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
    @user = current_user
  end

  def show
      @user = User.find_by(id: params[:id])
      @contents = @user.contents
      @mycontents_count = @user.contents.ids.count
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = "#{@user} のプロフィールを編集が完了しました"
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  def following
      @user  = User.find(params[:id])
      @users = @user.followings
      render 'show_follow'
  end

  def followers
    @user  = User.find(params[:id])
    @users = @user.followers
    render 'show_follower'
  end

 private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation,:avatar)
  end

  def set_user
   @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def current_user?(user)
     user == current_user
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tsundoku?</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'partial/navbar' %>
    <%= render "partial/flash_alert" %>
    <% if flash[:notice] %>
      <div class="alert alert-info">
        <%= flash[:notice] %>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class="alert alert-danger">
        <%= flash[:alert] %>
      </div>
    <% end %>
    <%= yield %>
    <%= render 'partial/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Home</title>
  </head>
  <body>
    <% if user_signed_in? %> 
  <%= link_to "サインアウト", destroy_user_session_path, method: :delete %>
  <% end %>


    <p>かりのとっぷ</p>
    <%= link_to "仮のボタンです", "#", class: "btn btn-primary" %>
  </body>
</html>

app/views/partial/_footer.html.erb
<footer>
  <div class="container">
    <div class="text-center">
      <p>
        Copyright © ポートフォリオ
      </p>
    </div>
  </div>
</footer>

app/views/partial/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light">
  <div class="container">
    <%= link_to "", root_path, class: "navbar__brand navbar__mainLogo" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>


    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-md-auto align-items-center">

        <li class ="nav-item"><%= link_to "ユーザー一覧",users_path, class: "btn btn-primary" %></li>
        <li class ="nav-item"><% if user_signed_in? == false %>
          <%= link_to "ログイン", new_user_session_path, class: "list-group-item list-group-item-action" %>
        <% end %></li>



        <% if user_signed_in? %>
          <li>
            <%= link_to "投稿", new_content_path, class: "btn btn-primary" %>
            <%= link_to "投稿一覧", contents_path, class: "list-group-item list-group-item-action" %>
            <%= link_to "プロフィールを編集", edit_user_registration_path, class: "list-group-item list-group-item-action" %>
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "list-group-item list-group-item-action"%>
         </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>